# title=xTeVe
# description=M3U Proxy for Plex DVR and Emby Live TV
# logo=https://raw.githubusercontent.com/xteve-project/xTeVe/master/html/img/x_black.png
# categories=media,iptv

---
version: "3.2"

services:
  app:
    image: alturismo/xteve_g2g_owi
    restart: unless-stopped
    ports:
      - ${34400:-34400}:34400 # Exposed port
    environment:
      - TZ=${TZ:-Europe/Chisinau} # Timezone
    volumes:
      - ${ROOT_PATH:-/appdata/xteve/root}:/root/.xteve # Root path
      - ${CONFIG_PATH:-/appdata/xteve/_config/}:/config # Config path
      - ${GUIDE2GO_PATH:-/appdata/xteve/_guide2go/}:/guide2go # Guide2go path
      - ${OWI2PLEX_PATH:-/appdata/xteve/_owi2plex/}:/owi2plex # Owi2plex path
      - ${TVHEADEND_PATH:-/appdata/xteve/tvheadend/data/}:/TVH # Tvheadend path
      - ${TMP_PATH:-/tmp/xteve/}:/tmp/xteve # tmp path
