apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-operator-grafana-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: prometheus-operator-grafana
    namespace: monitoring
  hostPath:
    path: /var/local/grafana
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-operator-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: prometheus-operator-grafana-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-operator-prometheus-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: db-prometheus-prometheus-operator-kube-p-prometheus-0
    namespace: monitoring
  hostPath:
    path: /var/local/prometheus
    type: DirectoryOrCreate
