defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/hobroker/messenger
          tag: latest
          pullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "3000"
          - name: GCS_KEY_FILENAME
            value: "./gcs-credentials.json"
          - name: GCS_BUCKET_NAME
            value: "selfhosted-messenger"
          - name: TELEGRAM_TOKEN
            valueFrom:
              secretKeyRef:
                name: messenger-telegram-secret
                key: TELEGRAM_TOKEN
          - name: TELEGRAM_CHAT_ID
            valueFrom:
              secretKeyRef:
                name: messenger-telegram-secret
                key: TELEGRAM_CHAT_ID

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 3000

persistence:
  configmap:
    type: secret
    name: messenger-secret
    advancedMounts:
      main:
        main:
          - path: /usr/src/app/gcs-credentials.json
            subPath: gcs-credentials.json
