version: '3.3'
services:
  agent:
    image: swarmpit/agent:2.2
    environment:
      DOCKER_API_VERSION: '1.35'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        reservations:
          cpus: '0.05'
          memory: 32M
        limits:
          cpus: '0.1'
          memory: 64M
  app:
    image: swarmpit/swarmpit:1.9
    environment:
      SWARMPIT_DB: http://db:5984
      SWARMPIT_INFLUXDB: http://influxdb:8086
    ports:
      - 888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.5'
          memory: 1024M
  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          cpus: '0.15'
          memory: 128M
        limits:
          cpus: '0.3'
          memory: 256M
  influxdb:
    image: influxdb:1.7
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          cpus: '0.3'
          memory: 128M
        limits:
          cpus: '0.6'
          memory: 512M
networks:
  net:
    driver: overlay
volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
