version: '3.3'
services:
  pomerium:
    image: pomerium/pomerium:latest
    extra_hosts:
      - docker.host.internal:172.17.0.1
    environment:
      POLICY: ${POLICY}
      ADMINISTRATORS: ${ADMINISTRATORS}
      AUTHENTICATE_SERVICE_URL: ${AUTHENTICATE_SERVICE_URL}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SHARED_SECRET: ${SHARED_SECRET}
      IDP_CLIENT_ID: ${IDP_CLIENT_ID}
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
      IDP_PROVIDER: google
      IDP_PROVIDER_URL: https://accounts.google.com
      CERTIFICATE_FILE: /config/certs/fullchain.cer
      CERTIFICATE_KEY_FILE: /config/certs/certpriv.key
    ports:
      - 443:443
    volumes:
      - /appdata/pomerium/data:/data
      - /appdata/pomerium/sync:/config
    networks:
      - network
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
      resources:
        reservations:
          cpus: '0.2'
          memory: 200M
networks:
  network:
    driver: overlay
