defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: fyb3roptik/threadfin
          tag: 1.2.39
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 34400

persistence:
  config:
    existingClaim: threadfin-config-pvc
    globalMounts:
      - path: /home/threadfin/conf
  tmp:
    type: emptyDir
    globalMounts:
      - path: /tmp/threadfin
