replicaCount: 1

image:
  repository:
  tag:
  pullPolicy: IfNotPresent

services:
  - type: LoadBalancer
    suffix:
    ports:
      - protocol: TCP
        port: 80
        containerPort: 80

labels:

volumes:
#  - name: base-config
#    hostPath:
#      path: "/appdata/k3s/base"

volumeMounts:
#  - name: base-config
#    mountPath: "/config"

baseEnv:
  - name: PGID
    value: "1000"
  - name: PUID
    value: "1000"

waitForServices:
#  - test-service

args:

configmaps:

ingressRoutes:
#  websecure:
#    match: Host(`httpbin.hobroker.me`)
#    port: 80
#    middlewares:
#      - traefik-sso
