replicaCount: 1

image:
  repository:
  tag:
  pullPolicy: IfNotPresent

ports:
  - name: http
    port: 80
    containerPort: 80
    protocol: TCP

volumes:
  - name:
    hostPath:
    containerPath:

baseEnv:
  PGID: "1000"
  PUID: "1000"

env:
