base:
  replicaCount: 1

  image:
    repository: prom/prometheus
    tag: v2.29.2
    pullPolicy: IfNotPresent

  services:
    - type: LoadBalancer
      ports:
        - protocol: TCP
          port: 9090

  volumes:
    - name: prometheus-data
      hostPath:
        path: "/appdata/k3s/prometheus/data"
    - name: prometheus-config
      configMap:
        name: prometheus-config

  volumeMounts:
    - name: prometheus-data
      mountPath: "/prometheus"
    - name: prometheus-config
      subPath: prometheus.yml
      mountPath: "/etc/prometheus/prometheus.yml"
