# title=Sonarr
# description=TV Shows collection manager for Usenet and BitTorrent users
# logo=https://raw.githubusercontent.com/Sonarr/Sonarr/phantom-develop/Logo/256.png
# categories=media

---
version: "3.2"

services:
  app:
    image: ghcr.io/linuxserver/sonarr
    environment:
      - PUID=${PUID:-1000} # UserID
      - PGID=${PGID:-1000} # GroupID
      - TZ=${TZ:-Europe/Chisinau} # Timezone
    volumes:
      - ${CONFIG_PATH:-/appdata/sonarr}:/config # Appdata
      - ${TV_PATH:-/storage/tv-shows}:/tv # The TV Shows location
      - ${DOWNLOADS_PATH:-/storage/downloads}:/downloads # The downloads location
    ports:
      - ${PORT:-8989}:8989 # WebUI Port
