apiVersion: v1
kind: PersistentVolume
metadata:
  name: backrest-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/local/backrest/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backrest-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: backrest-data-pv
  resources:
    requests:
      storage: 5Gi
