defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/syncthing
          tag: 1.28.1
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 8384
  misc:
    type: NodePort
    controller: main
    primary: false
    ports:
      tcp:
        protocol: TCP
        port: 22000
        nodePort: 22000
      udp:
        protocol: UDP
        port: 22000
        nodePort: 22000
      discovery:
        protocol: UDP
        port: 21027
        nodePort: 21027

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/syncthing
    globalMounts:
      - path: /config
  storage:
    enabled: true
    type: hostPath
    hostPath: /mnt/wdata
    globalMounts:
      - path: /mnt/wdata

ingress:
  main:
    enabled: true
    hosts:
      - host: syncthing.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
