#no-touch#

---
version: "3.3"

services:
  # https://hub.docker.com/r/pomerium/pomerium
  pomerium:
    image: pomerium/pomerium
    networks:
      - network
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    extra_hosts:
      - docker.host.internal:172.17.0.1
    environment:
      - AUTHENTICATE_SERVICE_URL=https://auth.hobroker.me # Auth service URL
      - CERTIFICATE_FILE=/config/certs/fullchain.cer
      - CERTIFICATE_KEY_FILE=/config/certs/certpriv.key
      - SHARED_SECRET=${SHARED_SECRET} # Shared secret (head -c32 /dev/urandom | base64)
      - COOKIE_SECRET=${COOKIE_SECRET} # Cookie secret (head -c32 /dev/urandom | base64)
      - IDP_PROVIDER=google
      - IDP_PROVIDER_URL=https://accounts.google.com
      - IDP_CLIENT_ID=${GOOGLE_CLIENT_ID} #  Google Client ID
      - IDP_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} #  Google Client Secret
      - POLICY=${POMERIUM_POLICY} # Pomerium Policy (base64)
      - ADMINISTRATORS="igor.leahu24@gmail.com" # Pomerium Policy (base64)
    volumes:
      - /appdata/pomerium/data:/data:rw # Pomerium data location
      - /appdata/pomerium/sync:/config # Config directory location
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  network:
    driver: overlay
