base:
  image:
    repository: thomseddon/traefik-forward-auth
    tag: 2
    pullPolicy: IfNotPresent

  services:
    - type: ClusterIP
      ports:
        - port: 4181

  env:
    - name: INSECURE_COOKIE
      value: "false"
    - name: COOKIE_DOMAIN
      value: hobroker.me
    - name: URL_PATH
      value: /_oauth
    - name: AUTH_HOST
      value: auth.hobroker.me
    - name: WHITELIST
      value: igor.leahu24@gmail.com
    - name: PROVIDERS_GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: traefik-secret
          key: PROVIDERS_GOOGLE_CLIENT_ID
    - name: PROVIDERS_GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: traefik-secret
          key: PROVIDERS_GOOGLE_CLIENT_SECRET
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: traefik-secret
          key: COOKIE_SECRET

  ingressRoutes:
    websecure:
      match: Host(`auth.hobroker.me`)
      port: 4181
      middlewares:
        - name: traefik-sso
