admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true
manager:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
  collectorImage:
    repository: "otel/opentelemetry-collector-contrib"
crds:
  create: true
