global:
  domain: argo.hobroker.me

configs:
  params:
    server.insecure: true # terminate TLS at Traefik, serve HTTP internally
  cm:
    resource.customizations.ignoreDifferences.apps_Deployment: |
      jsonPointers:
        - /status

server:
  service:
    type: LoadBalancer
    annotations:
      metallb.io/loadBalancerIPs: 192.168.50.202

  metrics:
    enabled: true

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hostname: argo.hobroker.me
