apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-wakatime-secret
  namespace: monitoring
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kira
        envSlug: prod
        secretsPath: "/wakatime"
        recursive: true
      credentialsRef:
          secretName: universal-auth-credentials
          secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: infisical-wakatime-secret
      secretNamespace: monitoring
      creationPolicy: "Owner"
      template:
        includeAllSecrets: true
