apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    category: system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      path: charts/system/infisical-operator/config
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
      chart: secrets-operator
      targetRevision: 0.10.25
      helm:
        releaseName: infisical
        valueFiles:
          - $values/charts/system/infisical-operator/values.yaml
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical-operator-system
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
