apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-acme-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/local/traefik/acme
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-acme-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: traefik-acme-pv
  resources:
    requests:
      storage: 100Mi
