additionalArguments:
  - --api
  - --api.dashboard=true
  - --api.insecure=true
  - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
  - --certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
  - --certificatesresolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=0

service:
  enabled: true
  type: LoadBalancer
  externalIPs:
    - 192.168.50.7
  spec:
    externalTrafficPolicy: Local

ports:
  traefik:
    expose:
      default: true
  web:
    expose:
      default: false
  websecure:
    http3:
      enabled: true

metrics:
  prometheus:
    service:
      enabled: true
    serviceMonitor:
      enabled: true
      jobLabel: traefik

deployment:
  additionalVolumes:
    - name: traefik-acme
      hostPath:
        path: "/appdata/k3s/traefik/acme"
  podAnnotations:
    secret.reloader.stakater.com/reload: "infisical-traefik-secret"

additionalVolumeMounts:
  - name: traefik-acme
    mountPath: "/acme"

securityContext:
  capabilities:
  readOnlyRootFilesystem:
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

envFrom:
  - secretRef:
      name: infisical-traefik-secret

logs:
  general:
    level: INFO

providers:
  kubernetesCRD:
    allowCrossNamespace: true
