defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/radarr
          tag: 6.0.2-develop
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 7878

serviceMonitor:
  metrics:
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-metrics'
    enabled: true
    endpoints:
      - port: http

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/radarr
    globalMounts:
      - path: /config
  storage:
    enabled: true
    type: hostPath
    hostPath: /mnt/nebula/movies
    globalMounts:
      - path: /mnt/nebula/movies
  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/nebula/downloads
    globalMounts:
      - path: /downloads

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: radarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
