defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/radarr
          tag: 5.19.3-develop
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"
  metrics:
    pod:
      annotations:
        secret.reloader.stakater.com/reload: "infisical-exportarr-radarr-secret"
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.0.1
          pullPolicy: IfNotPresent
        args: ["radarr"]
        env:
          - name: URL
            value: "http://radarr-main:7878"
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: infisical-exportarr-radarr-secret
                key: APIKEY

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 7878
  metrics:
    controller: metrics
    type: ClusterIP
    ports:
      http:
        port: 9707

serviceMonitor:
  metrics:
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-metrics'
    enabled: true
    endpoints:
      - port: http

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/radarr
    globalMounts:
      - path: /config
  storage:
    enabled: true
    type: hostPath
    hostPath: /storage/movies
    globalMounts:
      - path: /movies
  downloads:
    enabled: true
    type: hostPath
    hostPath: /storage/downloads
    globalMounts:
      - path: /downloads

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: radarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
