defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/radarr
          tag: 5.2.6
          pullPolicy: IfNotPresent

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 7878

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/radarr
    globalMounts:
      - path: /config
  storage:
    enabled: true
    type: hostPath
    hostPath: /storage/movies
    globalMounts:
      - path: /movies
  downloads:
    enabled: true
    type: hostPath
    hostPath: /storage/downloads
    globalMounts:
      - path: /downloads

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - host: radarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
