repositories:
  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts

releases:
  - name: prowlarr
    version: 3.6.1
    atomic: true
    namespace: self
    chart: bjw-s/app-template
    values:
      - values.yaml
