defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/prowlarr
          tag: 2.0.5
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 9696

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/prowlarr
    globalMounts:
      - path: /config

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: prowlarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
