defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/prowlarr
          tag: 1.37.0
          pullPolicy: IfNotPresent
  metrics:
    pod:
      annotations:
        secret.reloader.stakater.com/reload: "infisical-exportarr-prowlarr-secret"
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.2.0
          pullPolicy: IfNotPresent
        args: ["prowlarr"]
        env:
          - name: URL
            value: "http://prowlarr-main:9696"
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: infisical-exportarr-prowlarr-secret
                key: APIKEY

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 9696
  metrics:
    controller: metrics
    type: ClusterIP
    ports:
      http:
        port: 9707

serviceMonitor:
  metrics:
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-metrics'
    enabled: true
    endpoints:
      - port: http

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/prowlarr
    globalMounts:
      - path: /config

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: prowlarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
