apiVersion: v2
name: traefik
description: Traefik chart
icon: https://
type: application
version: 0.1.0
appVersion: "v2.8.0"
dependencies:
  - name: traefik
    version: 10.24.0
    repository: https://helm.traefik.io/traefik
