apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-traefik-secret
  namespace: kube-system
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kira
        envSlug: prod
        secretsPath: "/traefik"
        recursive: true
      credentialsRef:
          secretName: universal-auth-credentials
          secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: infisical-traefik-secret
      secretNamespace: kube-system
      creationPolicy: "Owner"
      template:
        includeAllSecrets: true
