apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 6}}
        {{- end }}
      initContainers:
        {{- range .Values.waitForServices }}
        - name: wait-for-{{ . }}
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command:
            - sh
            - -c
            - |
              until nslookup {{ . }}; do
                echo waiting for {{ . }};
                sleep 2;
              done
        {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.args }}
              {{- toYaml .Values.args | nindent 12 }}
            {{- end }}
          ports:
            {{- range .Values.services }}
            {{- range .ports }}
            - containerPort: {{ .containerPort | default .port }}
              protocol: {{ .protocol | default "TCP" | quote }}
            {{- end }}
            {{- end }}
          env:
            {{- if .Values.baseEnv }}
              {{- toYaml .Values.baseEnv | nindent 12 }}
            {{- end }}
            {{- if .Values.env }}
              {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.volumeMounts }}
              {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
