{{- $releaseName := .Release.Name }}
  {{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-service{{ .suffix }}
spec:
  type: {{ .type }}
  selector:
    app: {{ $releaseName }}
  ports:
    {{- $serviceType := .type }}
    {{- range .ports }}
    - name: {{ .protocol | default "TCP" | lower }}-{{ .containerPort }}
      protocol: {{ .protocol | default "TCP" | quote }}
      targetPort: {{ .containerPort }}
      port: {{ .port }}
      {{- if eq $serviceType "NodePort" }}
      nodePort: {{ .port }}
      {{- end }}
    {{- end }}
{{- end }}
