version: '3.3'
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    pid: host
    network_mode: host
    volumes:
      - '/:/host:ro,rslave'
