repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

releases:
  - name: vault
    version: 0.30.0
    namespace: vault
    chart: hashicorp/vault
    values:
      - vault-values.yaml

  - name: vault-secrets-operator
    version: 0.10.0
    atomic: true
    namespace: vault-secrets-operator-system
    chart: hashicorp/vault-secrets-operator
    values:
      - vault-operator-values.yaml
