repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

releases:
  - name: vault
    version: 0.28.1
    namespace: vault
    chart: hashicorp/vault
    values:
      - vault-values.yaml

  - name: vault-secrets-operator
    version: 0.8.1
    atomic: true
    namespace: vault-secrets-operator-system
    chart: hashicorp/vault-secrets-operator
    values:
      - vault-operator-values.yaml
