# title=Jackett
# description=API Support for your favorite torrent trackers
# logo=https://raw.githubusercontent.com/Jackett/Jackett/master/src/Jackett.Common/Content/apple-touch-icon.png
# categories=media

---
version: "3.2"

services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000} # UserID
      - PGID=${PGID:-1000} # GroupID
      - TZ=${TZ:-Europe/Chisinau} # Timezone
    volumes:
      - ${CONFIG:-/appdata/jackett}:/config # Config path
      - ${BLACKHOLE}:/downloads # Blackhole path
    ports:
      - ${PORT:-9117}:9117 # WebUI Port
