apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-https-echo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    category: demo
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.0.1
      helm:
        valueFiles:
          - $values/charts/demo/http-https-echo/values.yaml
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: self
  syncPolicy: {}
