defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: mendhak/http-https-echo
          tag: 36
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: demo.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
