defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: mendhak/http-https-echo
          tag: 35
          pullPolicy: IfNotPresent

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - host: demo.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
