defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: garethgeorge/backrest
          tag: v1.12.1
          pullPolicy: IfNotPresent
        env:
          BACKREST_CONFIG: /data/config.json
          BACKREST_DATA: /data
          GOOGLE_APPLICATION_CREDENTIALS: /data/credentials/gcs-key.json
          GOOGLE_PROJECT_ID: "crashplan-334916"

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 9898

persistence:
  data:
    existingClaim: backrest-data-pvc
    globalMounts:
      - path: /data
  varlocal:
    existingClaim: backrest-varlocal-pvc
    globalMounts:
      - path: /var/local
