replicaCount: 1

image:
  repository: linuxserver/plex
  tag: 1.32.8

services:
  - type: LoadBalancer
    ports:
      - port: 32400
        name: http
        containerPort: 32400
  - type: NodePort
    suffix: -discovery
    ports:
      - protocol: UDP
        name: udp-32410
        port: 32410
      - protocol: UDP
        name: udp-32412
        port: 32412
      - protocol: UDP
        name: udp-32413
        port: 32413
      - protocol: UDP
        name: udp-32414
        port: 32414

volumes:
  - name: plex-config
    hostPath:
      path: "/appdata/k3s/plex"
  - name: plex-storage
    hostPath:
      path: "/storage"
  - name: plex-storage2
    hostPath:
      path: "/mnt/onetb"
  - name: plex-pictures
    hostPath:
      path: "/mnt/wdata/photos"

volumeMounts:
  - name: plex-config
    mountPath: "/config"
  - name: plex-storage
    mountPath: "/storage"
  - name: plex-storage2
    mountPath: "/storage2"
  - name: plex-pictures
    mountPath: "/photos"

env:
  - name: UMASK
    value: "022"
  - name: VERSION
    value: "latest"

ingressRoutes:
  websecure:
    match: Host(`plex.hobroker.me`)
    port: 32400
