apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-volume
  labels:
    type: local
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/appdata/k8s-jackett"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
