{
 "title": "Scraparr",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(scraparr_services_up,job)"
    }
   },
   {
    "name": "prowlarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"prowlarr\"},alias)"
    }
   },
   {
    "name": "sonarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"sonarr\"},alias)"
    }
   },
   {
    "name": "radarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"radarr\"},alias)"
    }
   },
   {
    "name": "bazarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"bazarr\"},alias)"
    }
   },
   {
    "name": "readarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"readarr\"},alias)"
    }
   },
   {
    "name": "seerr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=~\"jellyseerr|overseerr\"},alias)"
    }
   },
   {
    "name": "kavita",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=~\"kavita\"},alias)"
    }
   },
   {
    "name": "kavita_libraries",
    "query": {
     "query": "label_values(kavita_library_type{alias=~\"kavita\"},library)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"sonarr\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_build_time{job=~\"$job\", alias=\"$sonarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sonarr_last_scrape{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sonarr_start_time{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total/Missing Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Episodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_episodes_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_missing_episodes_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total/Monitored/Ended/Continuing Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Series" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_series_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_monitored_series_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_ended_series{job=~\"$job\", path=\"total\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_continuing_series{job=~\"$job\", path=\"total\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_disk_size{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_disk_size_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_free_disk_size{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quality Episode",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Episode" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sonarr_quality_episodes_total{job=~\"$job\", alias=\"$sonarr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genres Episode",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Episodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sonarr_genres_count_total{job=~\"$job\", alias=\"$sonarr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"radarr\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_build_time{job=~\"$job\", alias=\"$radarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - radarr_last_scrape{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - radarr_start_time{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total/Downloaded/Monitored/Missing Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Movies" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "radarr_movies_total{job=~\"$job\", alias=\"$radarr\"} - radarr_missing_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "radarr_monitored_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "radarr_missing_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_disk_size{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "radarr_disk_size_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_free_disk_size{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quality's",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Movies" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(radarr_quality_movies_total{job=~\"$job\", alias=\"$radarr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genres",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Movies" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(radarr_genres_count_total{job=~\"$job\", alias=\"$radarr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Prowlarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"prowlarr\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_build_time{job=~\"$job\", alias=\"$prowlarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prowlarr_last_scrape{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prowlarr_start_time{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_applications_total{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enabled Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_application_enabled_total{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Sync-Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_application_sync_level_total{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_count{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enabled Indexers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_enabled{job=~\"$job\", indexer=\"total\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer Privacy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_privacy{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer VIP Expire in",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_vip_expiration{job=~\"$job\", alias=\"$prowlarr\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bazarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"bazarr\", alias=\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_build_time{job=~\"$job\", alias=\"$bazarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - bazarr_last_scrape{job=~\"$job\", alias=\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - bazarr_start_time{job=~\"$job\", alias=\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitored Media",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_movies_total{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bazarr_series_total{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wanted Media",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_wanted_movies_total{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bazarr_wanted_episodes_total{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Providers Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_providers{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Providers Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_provider_status{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}