repositories:
  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts

releases:
  - name: adguard-exporter
    version: 3.1.0
    atomic: true
    namespace: monitoring
    chart: bjw-s/app-template
    values:
      - values.yaml
