apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-exportarr-prowlarr-secret
  namespace: self
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kira
        envSlug: prod
        secretsPath: "/exportarr-prowlarr"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: infisical-exportarr-prowlarr-secret
      secretNamespace: self
      creationPolicy: "Owner"
      template:
        includeAllSecrets: true
