additionalArguments:
  - --api
  - --api.dashboard=true
  - --api.insecure=true
  - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
  - --certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
  - --certificatesresolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=0

service:
  enabled: true
  type: LoadBalancer
  externalIPs:
    - 192.168.29.242

ports:
  traefik:
    expose: true
  metrics:
    expose: true
    exposedPort: 9101

metrics:
  prometheus:
    disableAPICheck: true
    service:
      enabled: true
    serviceMonitor:
      jobLabel: traefik

deployment:
  additionalVolumes:
    - name: traefik-acme
      hostPath:
        path: "/appdata/k3s/traefik/acme"

additionalVolumeMounts:
  - name: traefik-acme
    mountPath: "/acme"

securityContext:
  capabilities:
  readOnlyRootFilesystem:
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: traefik-secret
        key: CF_API_EMAIL
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: CF_DNS_API_TOKEN
        name: traefik-secret

logs:
  general:
    level: INFO