defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/jackett
          tag: 0.21.1280
          pullPolicy: IfNotPresent

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 9117

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/jackett
    globalMounts:
      - path: /config/Jackett
  blackhole:
    enabled: true
    type: hostPath
    hostPath: /storage/downloads/torrents
    globalMounts:
      - path: /blackhole

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - host: jackett.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
