replicaCount: 1

namespace: self

image:
  repository:
  tag:
  pullPolicy: IfNotPresent

nodeName: kira-pc

restartOnConfigChange: true

services:
#  - type: LoadBalancer
#    suffix:
#    metadata:
#    ports:
#      - protocol: TCP
#        port: 80
#        containerPort: 80
#        name: http

serviceMonitor:
  release: prometheus-operator
#  enabled: true
#  endpoints:
#  - port: http
#    interval: 10s

labels:

volumes:
#  - name: base-config
#    hostPath:
#      path: "/appdata/k3s/base"

volumeMounts:
#  - name: base-config
#    mountPath: "/config"

baseEnv:
  - name: PGID
    value: "1000"
  - name: PUID
    value: "1000"

waitForServices:
#  - test-service

args:

configmaps:

ingressRoutes:
#  websecure:
#    match: Host(`httpbin.hobroker.me`)
#    port: 80
#    middlewares:
#      - traefik-sso
