apiVersion: batch/v1
kind: Job
metadata:
  name: recyclarr-sync
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: render-config
          image: bhgedigital/envsubst:latest
          command:
            - sh
            - -c
            - envsubst < /recyclarr-template/recyclarr.yml > /config/recyclarr.yml
          env:
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infisical-recyclarr-secret
                  key: sonarr_api_key
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infisical-recyclarr-secret
                  key: radarr_api_key
          volumeMounts:
            - name: config
              mountPath: /config
            - name: recyclarr-template
              mountPath: /recyclarr-template
      containers:
        - name: recyclarr
          image: ghcr.io/recyclarr/recyclarr:8
          args:
            - sync
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: recyclarr-config-pvc
        - name: recyclarr-template
          configMap:
            name: recyclarr-config
