defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/jellyfin
          tag: 10.11.0
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 8096

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/jellyfin
    globalMounts:
      - path: /config
  nebula:
    enabled: true
    type: hostPath
    hostPath: /mnt/nebula
    globalMounts:
      - path: /mnt/nebula

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    className: "traefik"
    hosts:
      - host: jellyfin.hobroker.me
        paths:
          - path: /
            pathType: Prefix

            service:
              identifier: main
