repositories:
  - name: bjw-s
    url: https://bjw-s-labs.github.io/helm-charts

releases:
  - name: bazarr
    version: 3.7.3
    atomic: true
    namespace: self
    chart: bjw-s/app-template
    values:
      - values.yaml
