defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/bazarr
          tag: 1.5.3
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 6767

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/bazarr
    globalMounts:
      - path: /config
  nebula:
    enabled: true
    type: hostPath
    hostPath: /mnt/nebula
    globalMounts:
      - path: /mnt/nebula

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: bazarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
