apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    category: automation
spec:
  project: default
  sources:
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      path: apps/automation/openclaw/config
    - repoURL: registry.gitlab.com/xrow-public/helm-openclaw/charts
      chart: openclaw
      targetRevision: 1.17.2
      helm:
        valueFiles:
          - $values/apps/automation/openclaw/values.yaml
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
