image:
  tag: 1.17.2

service:
  type: ClusterIP
  port: 18789

persistence:
  storageClass: ""
  size: 5Gi

config:
  timezone: Europe/Bucharest
  secrets: []

browserless:
  enabled: false

ingress:
  enabled: false
