version: '3.3'

services:
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - 8888:8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role == manager

