apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        app: prometheus-node-exporter
        name: prometheus-node-exporter
    spec:
      containers:
        - image: prom/node-exporter:v0.16.0
          imagePullPolicy: IfNotPresent
          name: prometheus-node-exporter
          ports:
            - name: prom-node-exp
              containerPort: 9100
              hostPort: 9100
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
      hostNetwork: true
      hostPID: true
      hostIPC: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    app: prometheus-node-exporter
  clusterIP: None
  ports:
    - name: prometheus-node-exporter
      port: 9100
      protocol: TCP
  type: ClusterIP
