repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    version: 7.8.23
    atomic: true
    namespace: argocd
    chart: argo/argo-cd
    values:
      - values.yaml
