repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    version: 6.7.3
    atomic: true
    namespace: argo
    createNamespace: true
    chart: argo/argo-cd
    values:
      - values.yaml
