global:
  domain: argo.hobroker.me

controller:
  metrics:
    serviceMonitor:
      enabled: true

server:
  ingress:
    enabled: true
  metrics:
    serviceMonitor:
      enabled: true

repoServer:
  metrics:
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    serviceMonitor:
      enabled: true

notifications:
  metrics:
    serviceMonitor:
      enabled: true

configs:
  params:
    application.namespaces: "biomarkers"
    server.insecure: true
