# title=Sonarr
# description=PVR for newsgroup and bittorrent users for downloading/organising TV shows
# logo=https://raw.githubusercontent.com/Sonarr/Sonarr/phantom-develop/Logo/256.png
# categories=media

---
version: "3.2"

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000} # UserID
      - PGID=${PGID:-1000} # GroupID
      - TZ=${TZ:-Europe/Chisinau} # Timezone
    volumes:
      - ${CONFIG_PATH:-/appdata/sonarr}:/config # App data
      - ${TV_PATH:-/mnt/storage/tv-shows}:/tv # The TV Shows location
      - ${DOWNLOADS_PATH:-/mnt/storage/downloads}:/downloads # The downloads location
    ports:
      - ${PORT:-8989}:8989 # WebUI Port
