apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recyclarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    category: media
spec:
  project: default
  sources:
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      path: apps/media/recyclarr/config
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.6.2
      helm:
        valueFiles:
          - $values/apps/media/recyclarr/values.yaml
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
