apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recyclarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    category: media
spec:
  project: default
  source:
    repoURL: https://github.com/hobroker/selfhosted.git
    targetRevision: HEAD
    path: apps/media/recyclarr/config
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
