controllers:
  main:
    type: cronjob
    cronjob:
      concurrencyPolicy: Forbid
      timeZone: Europe/Chisinau
      schedule: "0 0 * * *" # every day at midnight
      startingDeadlineSeconds: 30
      successfulJobsHistory: 1
      failedJobsHistory: 2
      backoffLimit: 3
    initContainers:
      render-config:
        image:
          repository: bhgedigital/envsubst
          tag: latest
          pullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - envsubst < /recyclarr-template/recyclarr.yml > /config/recyclarr.yml
        env:
          - name: SONARR_API_KEY
            valueFrom:
              secretKeyRef:
                name: infisical-recyclarr-secret
                key: sonarr_api_key
          - name: RADARR_API_KEY
            valueFrom:
              secretKeyRef:
                name: infisical-recyclarr-secret
                key: radarr_api_key
    containers:
      main:
        image:
          repository: ghcr.io/recyclarr/recyclarr
          tag: 8
          pullPolicy: IfNotPresent
        args:
          - sync

persistence:
  config:
    existingClaim: recyclarr-config-pvc
    globalMounts:
      - path: /config
  recyclarr-template:
    type: configMap
    name: recyclarr-config
    advancedMounts:
      main:
        render-config:
          - path: /recyclarr-template/recyclarr.yml
            subPath: recyclarr.yml
