version: '3.3'
services:
  ombi:
    image: ghcr.io/linuxserver/ombi:latest
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Chisinau
      UMASK_SET: '022'
    ports:
      - 3579:3579
    volumes:
      - /appdata/ombi:/config
    networks:
      - default
    logging:
      driver: json-file
networks:
  chief_network:
    external: true
  default:
    driver: overlay
