# title=Plex
# description=Media player and organizational tool for accessing videos, music and pictures
# logo=https://raw.githubusercontent.com/plexinc/plex-media-player/master/resources/images/icon.png
# categories=media

---
version: '3.2'

services:
  plex:
    image: ghcr.io/linuxserver/plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000} # UserID
      - PGID=${PGID:-1000} # GroupID
      - UMASK_SET=${UMASK_SET:-022} # Plex file-creation mode
      - VERSION=docker #
      - PLEX_CLAIM= # Claim at https://plex.tv/claim
    ports:
      - target: 32400
        published: 32400 # WebUI Port
        protocol: tcp
        mode: host
      - 1900:1900/udp # Plex DLNA Server
      - 3005:3005 # Control Plex Home Theater via Plex Companion
      - 5353:5353/udp # Old Bonjour/Avahi network discovery
      - 32410:32410/udp # GDM network discovery
      - 32412:32412/udp # GDM network discovery
      - 32413:32413/udp # GDM network discovery
      - 32414:32414/udp # GDM network discovery
      - 32469:32469 # Plex DLNA Server
    volumes:
      - ${APPDATA:-/appdata/plex}:/config # Plex appdata location
      - ${STORAGE:-/mnt/storage}:/mnt/storage # Media library location 1
      - ${STORAGE:-/storage}:/storage # Media library location 2
