# title=Plex
# description=Media player and organizational tool for accessing videos, music and pictures
# logo=https://raw.githubusercontent.com/plexinc/plex-media-player/master/resources/images/icon.png
# categories=media

---
version: "2.4"

services:
  app:
    image: ghcr.io/linuxserver/plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000} # UserID
      - PGID=${PGID:-1000} # GroupID
      - UMASK_SET=${UMASK_SET:-022} # Plex file-creation mode
      - VERSION=docker #
      - PLEX_CLAIM= # Claim at https://plex.tv/claim
    volumes:
      - ${APPDATA:-/appdata/plex}:/config # Plex appdata location
      - ${STORAGE:-/mnt/storage}:/mnt/storage # Media library location
