apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/local/radarr
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: radarr-config-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies-pv
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.50.7
    path: /mnt/nebula/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: radarr-movies-pv
  resources:
    requests:
      storage: 100Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads-pv
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.50.7
    path: /mnt/nebula/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: radarr-downloads-pv
  resources:
    requests:
      storage: 100Ti
