defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/overseerr
          tag: 1.33.2
          pullPolicy: IfNotPresent

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 5055

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/overseerr
    globalMounts:
      - path: /config

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - host: overseerr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
