defaultPodOptions:
  automountServiceAccountToken: false
  securityContext:
    privileged: true

controllers:
  main:
    containers:
      main:
        image:
          repository: koenkk/zigbee2mqtt
          tag: 1.33.2
          pullPolicy: IfNotPresent

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 8080
        targetPort: 8087

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/zigbee2mqtt/data
    globalMounts:
      - path: /app/data
  udev:
    enabled: true
    type: hostPath
    hostPath: /run/udev
    globalMounts:
      - path: /run/udev
        readOnly: true
  usb:
    enabled: true
    type: hostPath
    hostPath: /dev/ttyUSB0
    globalMounts:
      - path: /dev/zigbee
