#no-touch#

---
version: "3.3"

services:
  # https://hub.docker.com/r/linuxserver/plex
  app:
    image: ghcr.io/linuxserver/plex
    networks:
      - chief_network
    ports:
      - target: 32400
        published: 32400 # WebUI Port
        protocol: tcp
        mode: host
      - 1900:1900/udp # Plex DLNA Server
      - 3005:3005 # Control Plex Home Theater via Plex Companion
      - 5353:5353/udp # Old Bonjour/Avahi network discovery
      - 32410:32410/udp # GDM network discovery
      - 32412:32412/udp # GDM network discovery
      - 32413:32413/udp # GDM network discovery
      - 32414:32414/udp # GDM network discovery
      - 32469:32469 # Plex DLNA Server
    environment:
      - PUID=1000 # UserID
      - PGID=1000 # GroupID
      - UMASK_SET=022 # Plex file-creation mode
      - TZ=Europe/Chisinau # Timezone
      - VERSION=docker # Do not update PLEX internally
      - PLEX_CLAIM= # Claim at https://plex.tv/claim
    volumes:
      - /appdata/plex:/config # Plex appdata location
      - /mnt/storage:/mnt/storage # Media library location 1
      - /storage:/storage # Media library location 2

  # https://hub.docker.com/r/tautulli/tautulli
  tautulli:
    image: tautulli/tautulli
    networks:
      - chief_network
    ports:
      - 8181:8181 # WebUI Port
    environment:
      - PUID=1000 # UserID
      - PGID=1000 # GroupID
      - UMASK_SET=022 # Plex file-creation mode
      - TZ=Europe/Chisinau # Timezone
    volumes:
      - /appdata/tautulli:/config # Tautulli config and database

  # https://hub.docker.com/r/alturismo/xteve_g2g_owi
  xteve:
    image: tnwhitwell/xteve
    networks:
      - chief_network
    ports:
      - 34400:34400 # Exposed port
    environment:
      - PUID=1000 # UserID
      - PGID=1000 # GroupID
      - UMASK_SET=022 # Plex file-creation mode
      - TZ=Europe/Chisinau # Timezone
    volumes:
      - /appdata/xteve/root:/config # Root path
      - /tmp/xteve:/tmp/xteve # tmp path

networks:
  chief_network:
    external: true
