defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/qbittorrent
          tag: 5.1.0
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"
          WEBUI_PORT: "8112"
  metrics:
    containers:
      main:
        image:
          repository: esanchezm/prometheus-qbittorrent-exporter
          tag: sha-c6100e5
          pullPolicy: IfNotPresent
        env:
          - name: QBITTORRENT_PORT
            value: "8112"
          - name: QBITTORRENT_HOST
            value: "qbittorrent-main"

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 8112
  metrics:
    controller: metrics
    type: ClusterIP
    ports:
      http:
        port: 8000

serviceMonitor:
  metrics:
    serviceName: '{{ include "bjw-s.common.lib.chart.names.name" $ }}-metrics'
    enabled: true
    endpoints:
      - port: http

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/qbittorrent
    globalMounts:
      - path: /config/qBittorrent
  blackhole:
    enabled: true
    type: hostPath
    hostPath: /storage/downloads/torrents
    globalMounts:
      - path: /blackhole
  downloads:
    enabled: true
    type: hostPath
    hostPath: /storage/downloads
    globalMounts:
      - path: /downloads

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: qbittorrent.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
