defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/qbittorrent
          tag: 5.0.3
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"
          WEBUI_PORT: "8112"

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 8112

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/qbittorrent
    globalMounts:
      - path: /config
  blackhole:
    enabled: true
    type: hostPath
    hostPath: /storage/downloads/torrents
    globalMounts:
      - path: /blackhole
  downloads:
    enabled: true
    type: hostPath
    hostPath: /storage/downloads
    globalMounts:
      - path: /downloads

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: qbittorrent.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
