apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.restartOnConfigChange }}
      annotations:
        checksum/config: {{ .Values.configmaps | toYaml | toString | sha256sum }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}
        name: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 6}}
      {{- end }}
      {{- if .Values.waitForServices }}
      initContainers:
        {{- range .Values.waitForServices }}
        - name: wait-for-{{ . }}
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command:
            - sh
            - -c
            - |
              until nslookup {{ . }}; do
                echo waiting for {{ . }};
                sleep 2;
              done
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          ports:
            {{- range .Values.services }}
            {{- range .ports }}
            {{- $protocol := .protocol | default "TCP" }}
            - containerPort: {{ .containerPort | default .port }}
              protocol: {{ .protocol | default "TCP" | quote }}
              name: {{ $protocol | lower }}-{{ .containerPort | default .port }}
            {{- end }}
            {{- end }}
          env:
            {{- if .Values.baseEnv }}
              {{- toYaml .Values.baseEnv | nindent 12 }}
            {{- end }}
            {{- if .Values.env }}
              {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
