{{- $releaseName := .Release.Name }}
{{- range .Values.services }}
{{- $serviceName := print $releaseName (default "" .suffix) }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $releaseName }}
  {{- if .metadata }}
  {{- toYaml .metadata | nindent 2 }}
  {{- end }}
spec:
  type: {{ .type }}
  selector:
    app: {{ $releaseName }}
  ports:
    {{- $serviceType := .type }}
    {{- range .ports }}
    - name: {{ .name  }}
      protocol: {{ .protocol | default "TCP" | quote }}
      targetPort: {{ .containerPort | default .port }}
      port: {{ .port }}
      {{- if eq $serviceType "NodePort" }}
      nodePort: {{ .port }}
      {{- end }}
    {{- end }}
{{- end }}
