apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-grafana-secret
  namespace: monitoring
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kira
        envSlug: prod
        secretsPath: "/prometheus-operator/grafana"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: infisical-grafana-secret
      secretNamespace: monitoring
      creationPolicy: "Owner"
      secretType: Opaque
      template:
        includeAllSecrets: true
