repositories:
  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts

releases:
  - name: apprise
    version: 3.4.0
    atomic: true
    namespace: self
    chart: bjw-s/app-template
    values:
      - values.yaml
