defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/sonarr
          tag: 4.0.17-develop
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"

service:
  main:
    controller: main
    type: ClusterIP
    annotations:
      metallb.io/allow-shared-ip: shared
    ports:
      http:
        port: 8989

persistence:
  config:
    existingClaim: sonarr-config-pvc
    globalMounts:
      - path: /config
  nebula:
    existingClaim: sonarr-nebula-pvc
    globalMounts:
      - path: /mnt/nebula

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: sonarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
