prometheus:
  prometheusSpec:
    enableAdminAPI: true
    retention: 60d
    scrapeInterval: 1m
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5G
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - prometheus.hobroker.me

grafana:
  grafana.ini:
    users:
      auto_assign_org: true
      auto_assign_org_role: Viewer
    auth.proxy:
      enabled: true
      header_name: cf-access-authenticated-user-email
      header_property: email
      auto_sign_up: true
      enable_login_token: false
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - grafana.hobroker.me
  persistence:
    enabled: true
    size: 5Gi

alertmanager:
  ingress:
    enabled: false

kubeScheduler:
  enabled: false

kubeApiServer:
  enabled: false

kubeProxy:
  enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

# too many metrics being scraped
kubelet:
  serviceMonitor:
    metricRelabelings:
     - regex: apiserver_request_duration_seconds_bucket
       action: drop

defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: false
    windows: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
