apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-longhorn-secret
  namespace: longhorn-system
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kira
        envSlug: prod
        secretsPath: "/longhorn"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: infisical-longhorn-secret
      secretNamespace: longhorn-system
      creationPolicy: "Owner"
      secretType: Opaque
      template:
        includeAllSecrets: true
