replicaCount: 1

image:
  repository: koenkk/zigbee2mqtt
  tag: 1.33.2

services:
  - type: LoadBalancer
    ports:
      - port: 8087
        containerPort: 8080

volumes:
  - name: udev
    hostPath:
      path: "/run/udev"
  - name: zigbee2mqtt-config
    hostPath:
      path: "/appdata/k3s/zigbee2mqtt/data"
  - name: zigbee2mqtt-usb
    hostPath:
      path: "/dev/zigbee"

volumeMounts:
  - name: zigbee2mqtt-config
    mountPath: "/app/data"
  - name: udev
    mountPath: "/run/udev"
    readOnly: true
  - name: zigbee2mqtt-usb
    mountPath: "/dev/ttyUSB0"

securityContext:
  privileged: true
