prometheus:
  prometheusSpec:
    retention: 3660d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5G

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.hobroker.me

grafana:
  adminUser: admin
  adminPassword: admin
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.hobroker.me
  persistence:
    type: pvc
    enabled: true
    storageClassName: local-path
    size: 5G

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.hobroker.me
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5G
