apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'home_weather'
        scrape_interval: 10s
        static_configs:
          - targets: ['192.168.29.54:5000']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['172.17.0.1:9100']

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana-service:5000']

