version: '3.3'
services:
  basic-auth-plugin:
    image: openfaas/basic-auth-plugin:0.18.18
    environment:
      pass_filename: basic-auth-password
      secret_mount_path: /run/secrets/
      user_filename: basic-auth-user
    networks:
      - functions
    secrets:
      - basic-auth-password
      - basic-auth-user
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
        window: 380s
        max_attempts: 20
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
      resources:
        reservations:
          memory: 50M
  faas-swarm:
    image: openfaas/faas-swarm:0.9.0
    environment:
      DOCKER_API_VERSION: '1.30'
      basic_auth: 'false'
      read_timeout: 5m5s
      secret_mount_path: /run/secrets/
      write_timeout: 5m5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - functions
    secrets:
      - basic-auth-password
      - basic-auth-user
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
        window: 380s
        max_attempts: 20
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
      resources:
        reservations:
          memory: 100M
  gateway:
    image: openfaas/gateway:0.18.18
    extra_hosts:
      - prometheus:172.17.0.1
    environment:
      auth_proxy_pass_body: 'false'
      auth_proxy_url: ''
      basic_auth: 'false'
      direct_functions: 'true'
      direct_functions_suffix: ''
      dnsrr: 'true'
      faas_nats_address: nats
      faas_nats_port: '4222'
      functions_provider_url: http://faas-swarm:8080/
      max_idle_conns: '1024'
      max_idle_conns_per_host: '1024'
      read_timeout: 5m5s
      scale_from_zero: 'true'
      secret_mount_path: /run/secrets/
      upstream_timeout: 5m
      write_timeout: 5m5s
    ports:
      - 8080:8080
      - 8082:8082
    networks:
      - functions
    secrets:
      - basic-auth-password
      - basic-auth-user
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
        window: 380s
        max_attempts: 20
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        reservations:
          memory: 100M
  nats:
    image: nats-streaming:0.17.0
    command:
      - --store
      - memory
      - --cluster_id
      - faas-cluster
    networks:
      - functions
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        reservations:
          memory: 50M
        limits:
          memory: 125M
  queue-worker:
    image: openfaas/queue-worker:0.11.2
    environment:
      ack_wait: 5m5s
      basic_auth: 'false'
      faas_gateway_address: gateway
      gateway_invoke: 'true'
      max_inflight: '1'
      secret_mount_path: /run/secrets/
    networks:
      - functions
    secrets:
      - basic-auth-password
      - basic-auth-user
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
        window: 380s
        max_attempts: 20
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 50M
networks:
  functions:
    driver: overlay
secrets:
  basic-auth-password:
    external: true
  basic-auth-user:
    external: true
