defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: tautulli/tautulli
          tag: v2.14.3
          pullPolicy: IfNotPresent

service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 8181

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/tautulli
    advancedMounts:
      main:
        main:
          - path: /config

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - host: tautulli.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
