defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: tautulli/tautulli
          tag: v2.16.0
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8181

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/tautulli
    advancedMounts:
      main:
        main:
          - path: /config

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: tautulli.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
