# title=Pomerium
# description=Identity-aware access proxy that enables secure access to internal applications
# logo=https://raw.githubusercontent.com/pomerium/pomerium/master/docs/.vuepress/public/img/logo-round.png
# categories=network

---
version: "3.2"

services:
  pomerium:
    image: pomerium/pomerium:latest
    environment:
      - AUTHENTICATE_SERVICE_URL=${AUTHENTICATE_SERVICE_URL:-https://auth.hobroker.me} # Secret key
      - CERTIFICATE_FILE=/config/certs/fullchain.cer
      - CERTIFICATE_KEY_FILE=/config/certs/certpriv.key
      - SHARED_SECRET=EgMK3uYhqPeENCMnOx1roosDhZCj5Z59GpnC9eRZRDA=
      - COOKIE_SECRET=nvbo8rnH6ZqrTfC7uNGfXlLR3xJ0BFTaN9VCnJx9ipo=
      - IDP_PROVIDER=${IDP_PROVIDER:-google}
      - IDP_PROVIDER_URL=${IDP_PROVIDER_URL:-https://accounts.google.com}
      - IDP_CLIENT_ID=${IDP_CLIENT_ID} #  Google Client ID
      - IDP_CLIENT_SECRET=${IDP_CLIENT_SECRET} #  Google Client Secret
      - POLICY=${POLICY} # Policy (base64)
    volumes:
      - /appdata/pomerium/data:/data:rw # Pomerium data location
      - /appdata/pomerium/sync:/config # Config directory location
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    extra_hosts:
      - docker.host.internal:172.17.0.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
