import type { App, Edge } from "./graph.js";

export function renderMermaid(apps: App[], edges: Edge[]): string {
  const byCategory = new Map<string, App[]>();
  for (const app of apps) {
    if (!byCategory.has(app.category)) byCategory.set(app.category, []);
    byCategory.get(app.category)!.push(app);
  }

  const lines: string[] = ["graph TD"];

  for (const [category, categoryApps] of byCategory) {
    lines.push(`  subgraph ${category}`);
    for (const app of categoryApps) {
      lines.push(`    ${app.name}`);
    }
    lines.push("  end");
    lines.push("");
  }

  for (const edge of edges) {
    // Solid arrow for required deps, dashed for optional
    const arrow = edge.optional
      ? `-. ${edge.label} .->`
      : `-->|${edge.label}|`;
    lines.push(`  ${edge.from} ${arrow} ${edge.to}`);
  }

  return lines.join("\n");
}

function tableRows(edges: Edge[]): string {
  return edges.length > 0
    ? edges
        .map((e) => `| \`${e.from}\` | \`${e.to}\` | ${e.label} |`)
        .join("\n")
    : "| — | — | — |";
}

export function renderMarkdown(apps: App[], edges: Edge[]): string {
  const mermaid = renderMermaid(apps, edges);
  const required = edges.filter((e) => !e.optional);
  const optional = edges.filter((e) => e.optional);

  return [
    "# App Dependency Graph",
    "",
    "> Auto-generated by `packages/dep-graph`. Run `npm run dep-graph` to regenerate.",
    ">",
    "> To add a new dependency rule, edit `packages/dep-graph/src/rules.ts`.",
    "> Solid edges = required · Dashed edges = optional (app works without it).",
    "",
    "```mermaid",
    mermaid,
    "```",
    "",
    "## Required dependencies",
    "",
    "| App | Depends on | Reason |",
    "| --- | ---------- | ------ |",
    tableRows(required),
    "",
    "## Optional dependencies",
    "",
    "| App | Depends on | Reason |",
    "| --- | ---------- | ------ |",
    tableRows(optional),
    "",
  ].join("\n");
}
