# title=Nginx Proxy Manager
# description=Container for managing Nginx proxy hosts with a simple, powerful interface
# logo=https://raw.githubusercontent.com/jc21/nginx-proxy-manager/master/frontend/app-images/logo-256.png
# categories=network

---
version: "3.2"
services:
  app:
    image: jc21/nginx-proxy-manager:2
    ports:
      - ${PORT:-81}:81
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      DISABLE_IPV6: ${DISABLE_IPV6:-true} # Disable IPv6
    volumes:
      - ${CONFIG_JSON:-/appdata/nginx-proxy-manager/config.json}:/app/config/production.json # JSON Config
      - ${DB:-/appdata/nginx-proxy-manager/npm.db}:/app/npm.db # Database
      - ${DATA:-/appdata/nginx-proxy-manager/data}:/data # App data
      - ${LETSENCRYPT:-/appdata/nginx-proxy-manager/letsencrypt}:/etc/letsencrypt # Let's Encrypt data
    extra_hosts:
      - docker.host.internal:172.17.0.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
