defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: flaresolverr/flaresolverr
          tag: v3.4.1
          pullPolicy: IfNotPresent
        env:
          CAPTCHA_SOLVER: hcaptcha-solver

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8191
