defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/sonarr
          tag: develop-version-4.0.13.2933
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 8989

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/sonarr
    globalMounts:
      - path: /config
  nebula:
    enabled: true
    type: hostPath
    hostPath: /mnt/nebula/tvshows
    globalMounts:
      - path: /nebula/tvshows
  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/nebula/downloads
    globalMounts:
      - path: /downloads

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: sonarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
