defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/sonarr
          tag: develop-version-4.0.13.2933
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"
  metrics:
    pod:
      annotations:
        secret.reloader.stakater.com/reload: "infisical-exportarr-sonarr-secret"
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.3.0
          pullPolicy: IfNotPresent
        args: ["sonarr"]
        env:
          - name: URL
            value: "http://sonarr-main:8989"
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: infisical-exportarr-sonarr-secret
                key: APIKEY

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 8989
  metrics:
    controller: metrics
    type: ClusterIP
    ports:
      http:
        port: 9707

serviceMonitor:
  metrics:
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-metrics'
    enabled: true
    endpoints:
      - port: http

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/sonarr
    globalMounts:
      - path: /config
  nebula:
    enabled: true
    type: hostPath
    hostPath: /mnt/nebula/tvshows
    globalMounts:
      - path: /nebula/tvshows
  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/nebula/downloads
    globalMounts:
      - path: /downloads

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: sonarr.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
