apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wakatime-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    category: monitoring
spec:
  project: default
  sources:
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      path: charts/monitoring/wakatime-exporter/config
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.6.2
      helm:
        valueFiles:
          - $values/charts/monitoring/wakatime-exporter/values.yaml
    - repoURL: https://github.com/hobroker/selfhosted.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy: {}
