repositories:
  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts

releases:
  - name: wakatime-exporter
    version: 3.7.3
    atomic: true
    namespace: monitoring
    chart: bjw-s/app-template
    values:
      - values.yaml
