replicaCount: 1

image:
  repository: cloudflare/cloudflared
  tag: 2023.7.1

args:
  - tunnel
  - --config
  - /etc/cloudflared/config/config.yaml
  - run

volumes:
  - name: creds
    secret:
      secretName: tunnel-credentials
  - name: config
    configMap:
      name: cloudflared
      items:
        - key: config.yaml
          path: config.yaml

volumeMounts:
  - name: config
    mountPath: /etc/cloudflared/config
    readOnly: true
  - name: creds
    mountPath: /etc/cloudflared/creds
    readOnly: true

configmaps:
  cloudflared:
    config.yaml: |-
      tunnel: httpbin
      credentials-file: /etc/cloudflared/creds/credentials.json
      metrics: 0.0.0.0:2000
      no-autoupdate: true
      ingress:
        - hostname: jackett.hobroker.me
          service: http://jackett:9117
        - hostname: sonarr.hobroker.me
          service: http://sonarr:8989
        - hostname: radarr.hobroker.me
          service: http://radarr:7878
        - hostname: qbittorrent.hobroker.me
          service: http://qbittorrent:8112
        - hostname: home.hobroker.me
          service: http://home-assistant:8123
        - hostname: code.hobroker.me
          service: http://code-server:8433
        - hostname: tgmedia.hobroker.me
          service: http://tgmedia-api:3002
        - hostname: bazarr.hobroker.me
          service: http://bazarr:6767
        - hostname: biomarkers.hobroker.me
          service: http://biomarkers:3005
        - hostname: dashboard.hobroker.me
          service: http://kubernetes-dashboard:9091
        - service: http_status:404
