replicaCount: 1

image:
  repository: linuxserver/code-server
  tag: v3.11.1-ls91
  pullPolicy: IfNotPresent

services:
  - type: LoadBalancer
    ports:
      - port: 8443

volumes:
  - name: code-server-config
    hostPath:
      path: "/appdata/k3s/code-server"
  - name: appdata-mount
    hostPath:
      path: "/appdata"
  - name: compose-mount
    hostPath:
      path: "/home/kira/compose"

volumeMounts:
  - name: code-server-config
    mountPath: "/config"
  - name: appdata-mount
    mountPath: "/appdata"
  - name: compose-mount
    mountPath: "/compose"
