replicaCount: 1

image:
  repository: linuxserver/code-server
  tag: 4.19.1

services:
  - type: LoadBalancer
    ports:
      - port: 8443

volumes:
  - name: code-server-config
    hostPath:
      path: "/appdata/k3s/code-server"
  - name: appdata-mount
    hostPath:
      path: "/appdata"
  - name: compose-mount
    hostPath:
      path: "/home/kira/compose"
  - name: downloads-mount
    hostPath:
      path: "/storage/downloads"
  - name: ww-mount
    hostPath:
      path: "/storage/ww"

volumeMounts:
  - name: code-server-config
    mountPath: "/config"
  - name: appdata-mount
    mountPath: "/appdata"
  - name: compose-mount
    mountPath: "/compose"
  - name: downloads-mount
    mountPath: "/downloads"
  - name: ww-mount
    mountPath: "/ww"

ingressRoutes:
  websecure:
    match: Host(`code.hobroker.me`)
    port: 8443
