replicaCount: 1

image:
  repository: grafana/grafana
  tag: 8.1.2
  pullPolicy: IfNotPresent

services:
  - type: LoadBalancer
    ports:
      - protocol: TCP
        port: 5000
        containerPort: 3000

volumes:
  - name: grafana-lib
    hostPath:
      path: "/appdata/k3s/grafana/lib"

volumeMounts:
  - name: grafana-lib
    mountPath: "/var/lib/grafana"

env:
  - name: GF_SERVER_ROOT_URL
    value: "https://grafana.hobroker.me"
  - name: GF_STRAVA_DS_DATA_PATH
    value: "/var/lib/grafana/strava"
  - name: GF_INSTALL_PLUGINS
    value: "grafana-strava-datasource,grafana-worldmap-panel,grafana-piechart-panel,grafana-googlesheets-datasource"
  - name: GF_AUTH_PROXY_ENABLED
    value: "true"
  - name: GF_AUTH_PROXY_HEADER_NAME
    value: "X-Pomerium-Claim-Email"
  - name: GF_AUTH_PROXY_HEADER_PROPERTY
    value: "username"
  - name: GF_AUTH_PROXY_AUTO_SIGN_UP
    value: "true"
  - name: GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN
    value: "false"
  - name: GF_METRICS_ENABLED
    value: "true"
