replicaCount: 1

image:
  repository: kennethreitz/httpbin
  tag: latest
  pullPolicy: IfNotPresent

services:
  - type: LoadBalancer
    ports:
      - protocol: TCP
        port: 8080
        containerPort: 80
