replicaCount: 1

image:
  repository: influxdb
  tag: 2.1.1

services:
  - type: LoadBalancer
    ports:
      - port: 8086

volumes:
  - name: influxdb-config
    hostPath:
      path: "/appdata/k3s/influxdb/config"
  - name: influxdb-data
    hostPath:
      path: "/appdata/k3s/influxdb/data"

volumeMounts:
  - name: influxdb-config
    mountPath: "/etc/influxdb2"
  - name: influxdb-data
    mountPath: "/var/lib/influxdb2"

ingressRoutes:
  websecure:
    match: Host(`influxdb.hobroker.me`)
    port: 8086
    middlewares:
      - name: traefik-sso
