replicaCount: 1

image:
  repository: ghcr.io/hobroker/messenger
  tag: latest
  pullPolicy: Always

services:
  - type: LoadBalancer
    ports:
      - port: 8182
        containerPort: 3000

volumes:
  - name: messenger-secret
    secret:
      secretName: messenger-secret

volumeMounts:
  - name: messenger-secret
    mountPath: "/usr/src/app/gcs-credentials.json"
    subPath: gcs-credentials.json
    readOnly: true

env:
  - name: PORT
    value: "3000"
  - name: GCS_KEY_FILENAME
    value: "./gcs-credentials.json"
  - name: GCS_BUCKET_NAME
    value: "selfhosted-messenger"
  - name: TELEGRAM_TOKEN
    valueFrom:
      secretKeyRef:
        name: messenger-telegram-secret
        key: TELEGRAM_TOKEN
  - name: TELEGRAM_CHAT_ID
    valueFrom:
      secretKeyRef:
        name: messenger-telegram-secret
        key: TELEGRAM_CHAT_ID
