replicaCount: 1

image:
  repository: linuxserver/ombi
  tag: 4.22.5

services:
  - type: LoadBalancer
    ports:
      - port: 3579

volumes:
  - name: config
    hostPath:
      path: "/appdata/k3s/ombi"

volumeMounts:
  - name: config
    mountPath: "/config"

waitForServices:
  - plex
  - sonarr
  - radarr

ingressRoutes:
  websecure:
    match: Host(`ombi.hobroker.me`)
    port: 3579
    middlewares:
      - name: traefik-sso
