replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.37.0

restartOnConfigChange: false

services:
  - type: LoadBalancer
    ports:
      - protocol: TCP
        port: 9090

volumes:
  - name: prometheus-data
    hostPath:
      path: "/appdata/k3s/prometheus/data"
  - name: prometheus-configmap
    configMap:
      name: prometheus-configmap

volumeMounts:
  - name: prometheus-data
    mountPath: "/prometheus"
  - name: prometheus-configmap
    subPath: prometheus.yml
    mountPath: "/etc/prometheus/prometheus.yml"

ingressRoutes:
  websecure:
    match: Host(`prometheus.hobroker.me`)
    port: 9090
    middlewares:
      - name: traefik-sso

configmaps:
  prometheus-configmap:
    prometheus.yml: |-
      global:
        evaluation_interval: 60s
        scrape_interval: 15s
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
                - localhost:9090
        - job_name: home_weather
          scrape_interval: 10s
          static_configs:
            - targets:
                - 192.168.29.60
        - job_name: grafana
          static_configs:
            - targets:
                - grafana:5000
        - job_name: node-exporter
          static_configs:
            - targets:
                - prometheus-node-exporter:9100
        - job_name: adguard
          static_configs:
            - targets:
                - adguard-exporter:9617
        - job_name: traefik
          static_configs:
            - targets:
                - traefik:9100
        - job_name: wakatime
          static_configs:
            - targets:
                - wakatime-exporter:9212
        - job_name: hass
          scrape_interval: 30s
          metrics_path: /api/prometheus
          bearer_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkMTIxOTAxNmQwODc0YTdlYjFkOWU1OTlmOGYxMWRmZCIsImlhdCI6MTY2MDU1Mzg5OCwiZXhwIjoxOTc1OTEzODk4fQ.R7FpYl1JdbSzRwVmzBEvvrEddbNfq6pyy7H2ak0Qg0s"
          static_configs:
            - targets:
                - home-assistant:8123
        - job_name: rclone
          static_configs:
            - targets:
                - 192.168.29.242:5572
        - job_name: cloudflared
          static_configs:
            - targets:
                - cloudflared:2000
          basic_auth:
            username: 'admin'
            password: 'admin'
