replicaCount: 1

image:
  repository: linuxserver/qbittorrent
  tag: version-14.3.7.99202108032349-7395-0415c0c6fubuntu20.04.1
  pullPolicy: IfNotPresent

services:
  - type: LoadBalancer
    ports:
      - port: 8112

volumes:
  - name: qbittorrent-config
    hostPath:
      path: "/appdata/k3s/qbittorrent"
  - name: qbittorrent-blackhole
    hostPath:
      path: "/storage/downloads/torrents"
  - name: qbittorrent-downloads
    hostPath:
      path: "/storage/downloads"

volumeMounts:
  - name: qbittorrent-config
    mountPath: "/config/qBittorrent"
  - name: qbittorrent-blackhole
    mountPath: "/blackhole"
  - name: qbittorrent-downloads
    mountPath: "/downloads"

env:
  - name: WEBUI_PORT
    value: "8112"
