replicaCount: 1

image:
  repository: linuxserver/radarr
  tag: version-4.2.4.6635

services:
  - type: LoadBalancer
    ports:
      - port: 7878

volumes:
  - name: radarr-config
    hostPath:
      path: "/appdata/k3s/radarr"
  - name: storage-movies
    hostPath:
      path: "/storage/movies"
  - name: storage-downloads
    hostPath:
      path: "/storage/downloads"

volumeMounts:
  - name: radarr-config
    mountPath: "/config"
  - name: storage-movies
    mountPath: "/movies"
  - name: storage-downloads
    mountPath: "/downloads"

waitForServices:
  - qbittorrent
  - jackett

ingressRoutes:
  websecure:
    match: Host(`radarr.hobroker.me`)
    port: 7878
    middlewares:
      - name: traefik-sso
