replicaCount: 1

image:
  repository: rclone/rclone
  tag: latest

services:
  - type: LoadBalancer
    ports:
      - port: 5572

command:
  - "rclone rcd"
#
#args:
#  - --rc-web-gui
#  - --rc-addr :5572
#  - --rc-user admin
#  - --rc-pass password

volumes:
  - name: rclone-config
    hostPath:
      path: "/appdata/k3s/rclone"
  - name: storage
    hostPath:
      path: "/mnt/wdata"

volumeMounts:
  - name: rclone-config
    mountPath: "/config"
  - name: storage
    mountPath: "/data"
