replicaCount: 1

image:
  repository: ghcr.io/haveagitgat/tdarr
  tag: latest

services:
  - type: LoadBalancer
    ports:
      - port: 8265
      - port: 8266
      - port: 8267

volumes:
  - name: tdarr-config
    hostPath:
      path: "/appdata/k3s/tdarr/server/config"
  - name: tdarr-server
    hostPath:
      path: "/appdata/k3s/tdarr/server/server"
  - name: tdarr-logs
    hostPath:
      path: "/appdata/k3s/tdarr/server/logs"
  - name: tdarr-cache
    hostPath:
      path: "/appdata/k3s/tdarr/node/cache"
  - name: tdarr-media
    hostPath:
      path: "/storage"

volumeMounts:
  - name: tdarr-config
    mountPath: "/app/configs"
  - name: tdarr-logs
    mountPath: "/app/logs"
  - name: tdarr-media
    mountPath: "/media"
  - name: tdarr-cache
    mountPath: "/temp"

env:
  - name: webUIPort
    value: "8265"
  - name: nodeID
    value: "InternalNode"
  - name: internalNode
    value: "true"
  - name: serverIP
    value: "tdarr-media"
  - name: serverPort
    value: "8266"
