apiVersion: v1
kind: PersistentVolume
metadata:
  name: hermes-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: hermes
    namespace: default
  hostPath:
    path: /var/local/hermes
    type: DirectoryOrCreate
