defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/plex
          tag: 1.43.0
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"

service:
  main:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.50.200
    ports:
      http:
        port: 32400

persistence:
  config:
    existingClaim: plex-config-pvc
    globalMounts:
      - path: /config
  nebula:
    existingClaim: plex-nebula-pvc
    globalMounts:
      - path: /mnt/nebula

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    className: "traefik"
    hosts:
      - host: plex.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
