defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/plex
          tag: 1.41.9
          pullPolicy: IfNotPresent
        env:
          PGID: "1000"
          PUID: "1000"

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 32400

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/plex
    globalMounts:
      - path: /config
  storage:
    enabled: true
    type: hostPath
    hostPath: /storage
    globalMounts:
      - path: /storage
  storage2:
    enabled: true
    type: hostPath
    hostPath: /mnt/onetb
    globalMounts:
      - path: /storage2

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    className: "traefik"
    hosts:
      - host: plex.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
