apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-kopia-secret
  namespace: default
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kira
        envSlug: prod
        secretsPath: "/kopia"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: infisical-kopia-secret
      secretNamespace: default
      creationPolicy: "Owner"
      secretType: Opaque
      template:
        includeAllSecrets: true
