apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-scraparr-secret
  namespace: monitoring
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kira
        envSlug: prod
        secretsPath: "/scraparr"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: infisical-scraparr-secret
      secretNamespace: monitoring
      creationPolicy: "Owner"
      template:
        includeAllSecrets: true
