kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
  namespace: monitoring
spec:
  global:
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
      extraConfd:
        configMap:
          name: datadog-extra-configmap
  features:
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
          http:
            enabled: true
    apm:
      enabled: true
    logCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    sbom:
      enabled: true
      containerImage:
        enabled: true
