version: '3.3'
services:
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Chisinau
      UMASK_SET: '022'
    ports:
      - 7878:7878
    volumes:
      - /appdata/radarr:/config
      - /storage/movies:/movies
      - /storage/downloads:/downloads
    networks:
      - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role == manager
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Chisinau
      UMASK_SET: '022'
    ports:
      - 8989:8989
    volumes:
      - /appdata/sonarr:/config
      - /storage/tv-shows:/tv
      - /storage/downloads:/downloads
    networks:
      - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role ==manager
networks:
  default:
    driver: overlay
