controllers:
  main:
    containers:
      main:
        image:
          repository: jamesread/olivetin
          tag: 2024.12.11
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 1337

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /appdata/k3s/olivetin
    globalMounts:
      - path: /config

ingress:
  main:
    enabled: true
    hosts:
      - host: olivetin.hobroker.me
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
