base:
  replicaCount: 1

  image:
    repository: pomerium/pomerium
    tag: latest
    pullPolicy: IfNotPresent

  services:
    - type: LoadBalancer
      ports:
        - port: 80
        - port: 443

  volumes:
    - name: pomerium-config
      hostPath:
        path: "/appdata/k3s/pomerium/certs"
#    - name: pomerium-data
#      hostPath:
#        path: "/appdata/k3s/pomerium/data"

  volumeMounts:
    - name: pomerium-config
      mountPath: "/certs"
#    - name: pomerium-data
#      mountPath: "/data"

  env:
    - name: ADMINISTRATORS
      value: igor.leahu24@gmail.com
    - name: AUTHENTICATE_SERVICE_URL
      value: https://auth.hobroker.me
    - name: CERTIFICATE_FILE
      value: /certs/fullchain.cer
    - name: CERTIFICATE_KEY_FILE
      value: /certs/privkey.key
    - name: IDP_PROVIDER
      value: google
    - name: IDP_PROVIDER_URL
      value: https://accounts.google.com
    - name: JWT_CLAIMS_HEADERS
      value: email
    - name: IDP_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: pomerium-secret
          key: IDP_CLIENT_ID
    - name: IDP_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: pomerium-secret
          key: IDP_CLIENT_SECRET
    - name: COOKIE_SECRET
      valueFrom:
        secretKeyRef:
          name: pomerium-secret
          key: COOKIE_SECRET
    - name: SHARED_SECRET
      valueFrom:
        secretKeyRef:
          name: pomerium-secret
          key: SHARED_SECRET
    - name: POLICY
      valueFrom:
        configMapKeyRef:
          key: policy
          name: pomerium-config

# https://www.pomerium.io/reference/#policy
policy: |-
  - from: https://jackett.hobroker.me
    to: http://jackett:9117
    preserve_host_header: true
    allowed_users:
      - igor.leahu24@gmail.com

  - from: https://radarr.hobroker.me
    to: http://radarr:7878
    allowed_users:
      - igor.leahu24@gmail.com

  - from: https://sonarr.hobroker.me
    to: http://sonarr:8989
    allowed_users:
      - igor.leahu24@gmail.com

  - from: https://qbittorrent.hobroker.me
    to: http://qbittorrent:8112
    preserve_host_header: true
    allowed_users:
      - igor.leahu24@gmail.com

  - from: https://code.hobroker.me
    to: http://code-server:8443
    allow_websockets: true
    allowed_users:
      - igor.leahu24@gmail.com

  - from: https://grafana.hobroker.me
    to: http://grafana:5000
    preserve_host_header: true
    pass_identity_headers: true
    allowed_users:
      - igor.leahu24@gmail.com

  - from: https://plex.hobroker.me
    to: http://plex:32400
    allow_public_unauthenticated_access: true
    allow_websockets: true

  - from: https://tautulli.hobroker.me
    to: http://tautulli:8181
    preserve_host_header: true
    allow_public_unauthenticated_access: true

  - from: https://syncthing.hobroker.me
    to: http://syncthing:8384
    preserve_host_header: true
    allow_websockets: true
    allowed_users:
      - igor.leahu24@gmail.com
