name: Helm validate

on: push

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: pwd
    - run: ls
    - name: helm-check
      uses: igabaydulin/helm-check-action@0.2.0
      env:
        CHART_LOCATION: ./helm/*
