name: Terraform validate

on: [ push ]

jobs:
  labelDesign:
    name: Label design-review when approved by dev
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
      - run: terraform validate
