apiVersion: v1
kind: PersistentVolume
metadata:
  name: openclaw-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: openclaw-data-pvc
    namespace: default
  hostPath:
    path: /var/local/openclaw
    type: DirectoryOrCreate
